### ISSUE TITLE
fatal: detected dubious ownership in repository at ...

### ISSUE THREAD

**Issue by jakubmikita** [Bonus83/copy_commit_push_tag#1]
Hi, I'm running into an issue while committing to a different repository.

Here's my workflow step:

```
- name: Migrate to external repository
  uses: bonus83/copy_commit_push_tag@main
  env:
    API_TOKEN_GITHUB: ${{ secrets.WORKER_GITHUB_TOKEN }}
  with:
    source_file: 'nested/dir/'
    destination_repo: 'another-org/another-repo'
    destination_branch: 'master'
    user_email: ${{ secrets.WORKER_EMAIL }}
    user_name: ${{ secrets.WORKER_NAME }}
    commit_message: "build(package): version ${{ steps.vars.outputs.version }}"
    commit_tag: "${{ steps.vars.outputs.version }}"
    use_rsync: true
```

This produces an error:

```
[...]
tests/Unit/ExampleTest.php
tests/Unit/Helpers/
tests/Unit/Helpers/PriceTest.php
tests/Unit/Traits/
tests/Unit/Traits/Enums/
tests/Unit/Traits/Enums/AsArrayTest.php
+ cd /tmp/tmp.ccJjHA
+ '[' '!' -z  ]
+ '[' -z 'build(package): version 0.0.1' ]
+ echo 'Adding git commit'
+ git add .
sent 15.99M bytes  received 6.24K bytes  31.98M bytes/sec
total size is 15.96M  speedup is 1.00
Adding git commit
fatal: detected dubious ownership in repository at '/tmp/tmp.ccJjHA'
To add an exception for this directory, call:
	git config --global --add safe.directory /tmp/tmp.ccJjHA
```

I think you might be missing whitelisting the tmp dir, see this: https://stackoverflow.com/questions/71901632/fatal-error-unsafe-repository-home-repon-is-owned-by-someone-else
